import json
import requests
from django.http import JsonResponse
from django.shortcuts import render
from overpassify import overpassify

# Renders the main index page (Emergency Resources Home)
def index(request):
    # Renders the single-page application view handling the map and the UI structure
    return render(request, 'map_app/index.html')

# Endpoint to handle interactive map queries based on categorical click
def search_resources(request):
    try:
        # Get standard geographic coordinates passed from the frontend (default 0.0)
        lat = float(request.GET.get('lat', 0.0))
        lon = float(request.GET.get('lon', 0.0))
        # Get category selected by user (food, shelter, medical, rehab)
        category = request.GET.get('category', 'food')
        
        # Set scalable distance boundary around user (default 2000 meters)
        try:
            radius = int(request.GET.get('radius', 2000))
        except ValueError:
            radius = 2000 

        # Map frontend URL categories to specific strict OpenStreetMap (OSM) tags
        # Note: We use Regex() native to OverpassQL for multiple OR conditions.
        if category == 'food':
            # Looking for food banks or soup kitchens
            node_statement = f"my_nodes = Node(Around({radius}, {lat}, {lon}), amenity='social_facility', social_facility=Regex('food_bank|soup_kitchen'))"
        elif category == 'shelter':
            # Looking strictly for structural emergency shelters
            node_statement = f"my_nodes = Node(Around({radius}, {lat}, {lon}), amenity='social_facility', social_facility='shelter')"
        elif category == 'medical':
            # Looking for ERs, regional hospitals, or urgent clinics
            node_statement = f"my_nodes = Node(Around({radius}, {lat}, {lon}), amenity=Regex('hospital|clinic|doctors'))"
        elif category == 'rehab':
            # Looking specifically for rehabilitation medical centers
            node_statement = f"my_nodes = Node(Around({radius}, {lat}, {lon}), healthcare='rehabilitation')"
        else:
            # Drop malformed requests immediately and throw 400
            return JsonResponse({'error': 'Invalid category requested'}, status=400)

        # Construct python code snippet that the overpassify library will read
        # The node_statement dynamically interpolates the proper parameter constraints above
        code = f"""
def dummy():
    {node_statement}
    out(my_nodes, qt=True)
"""
        # Transpile python source code dynamically to OverpassQL language utilizing the overpassify Github repo
        query_str = overpassify(code.strip())

        # Clean up buggy double-quote artifacts occasionally generated by overpassify's Python AST string parser (e.g., ""hospital"")
        query_str = query_str.replace('""', '"')

        # Provide strict formatting wrapper for overpass API query payload: we explicitly request JSON back
        final_query = "[out:json];\n" + query_str
        
        # Dispatch the request to the central public Overpass API server
        overpass_url = "https://overpass-api.de/api/interpreter"
        response = requests.post(overpass_url, data={'data': final_query}, timeout=30)
        
        # Evaluate response from the map API and proxy the valid elements payload back to our Javascript frontend
        if response.status_code == 200:
            data = response.json()
            return JsonResponse({'elements': data.get('elements', [])})
        else:
            print("Failed Overpass Query:")
            print(final_query)
            print("Response:", response.status_code, response.content)
            return JsonResponse({'error': f"Overpass API error {response.status_code}"}, status=400)
    except Exception as e:
        # Capture critical server-side crash logic and pass to user
        return JsonResponse({'error': str(e)}, status=500)
